#!/usr/bin/env node
/**
 * Render design tokens from the single hand-edited source
 * (packages/ui/tokens/tokens.json — the Nuit token set, extracted verbatim
 * from the Penpot design library / docs/design-system.md, never invented
 * here) into every consumer format:
 *
 *   - packages/ui/src/tokens.ts                                        (TS)
 *   - packages/ui/src/tokens.css                                (plain CSS)
 *   - apps/ios/Sources/SwabCore/Generated/DesignTokens.swift          (iOS)
 *   - apps/android/.../ui/theme/DesignTokens.kt                    (Android)
 *
 * NEVER edit the generated files by hand — edit tokens/tokens.json and re-run:
 *   node packages/ui/scripts/generate.mjs           # render
 *   node packages/ui/scripts/generate.mjs --check   # exit 1 if renders are stale (CI)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(packageRoot, "..", "..");
const check = process.argv.includes("--check");

const BANNER =
  "GENERATED by packages/ui/scripts/generate.mjs from packages/ui/tokens/tokens.json — DO NOT EDIT BY HAND.";

const tokensPath = join(packageRoot, "tokens", "tokens.json");
const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));

// ---------------------------------------------------------------------------
// Naming helpers — tokens.json keys are kebab-case ("voile-2") or camelCase
// ("doneTitle"); each target language needs its own idiomatic identifier.
// ---------------------------------------------------------------------------

/** kebab-or-camel -> camelCase (Swift/TS property names). */
function toCamel(key) {
  return key.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/** kebab-or-camel -> SCREAMING_SNAKE_CASE (Kotlin const names). */
function toUpperSnake(key) {
  return key
    .replace(/-/g, "_")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase();
}

/** kebab-or-camel -> kebab-case (CSS custom property segments). */
function toKebab(key) {
  return key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/** camelCase group key -> PascalCase nested type name (Swift enum / Kotlin object). */
function pascalCase(key) {
  if (key === "otp") return "OTP";
  return key.charAt(0).toUpperCase() + key.slice(1);
}

function hexToRgbTriplet(hex) {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `${r}, ${g}, ${b}`;
}

/** Splits a "category.key" component reference, e.g. "radius.button" -> ["radius", "button"]. */
function splitRef(ref) {
  const [category, key] = ref.split(".");
  return { category, key };
}

/** Kotlin has no implicit Int -> Double conversion, even for literal arguments — force a decimal. */
function toKotlinDouble(v) {
  return Number.isInteger(v) ? `${v}.0` : `${v}`;
}

// ---------------------------------------------------------------------------
// packages/ui/src/tokens.ts
// ---------------------------------------------------------------------------

function buildTs() {
  const lines = [`// ${BANNER}`, ""];

  lines.push("export const colors = {");
  for (const [key, c] of Object.entries(tokens.color)) {
    if (c.opacity !== undefined) {
      lines.push(`  "${key}": { value: "${c.value}", opacity: ${c.opacity} },`);
    } else {
      lines.push(`  "${key}": "${c.value}",`);
    }
  }
  lines.push("} as const;", "");

  lines.push("export const typography = {");
  for (const [key, t] of Object.entries(tokens.typography)) {
    lines.push(
      `  ${key}: { family: "${t.family}", size: ${t.size}, weight: ${t.weight}, lineHeight: ${t.lineHeight}, letterSpacing: ${t.letterSpacing}, textTransform: "${t.textTransform}" },`,
    );
  }
  lines.push("} as const;", "");

  lines.push("export const spacing = {");
  for (const [key, v] of Object.entries(tokens.spacing)) {
    lines.push(`  ${key}: ${v},`);
  }
  lines.push("} as const;", "");

  lines.push("export const radius = {");
  for (const [key, v] of Object.entries(tokens.radius)) {
    lines.push(`  ${key}: ${v},`);
  }
  lines.push("} as const;", "");

  lines.push("export const component = {");
  for (const [groupKey, group] of Object.entries(tokens.component)) {
    lines.push(`  ${groupKey}: {`);
    for (const [k, v] of Object.entries(group)) {
      if (k.endsWith("Token")) {
        const { category, key } = splitRef(v);
        const outKey = k.slice(0, -"Token".length);
        const refExpr = category === "radius" ? `radius.${key}` : `colors["${key}"]`;
        lines.push(`    ${outKey}: ${refExpr},`);
      } else {
        lines.push(`    ${k}: ${typeof v === "string" ? `"${v}"` : v},`);
      }
    }
    lines.push("  },");
  }
  lines.push("} as const;", "");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// packages/ui/src/tokens.css
// ---------------------------------------------------------------------------

function buildCss() {
  const lines = [`/* ${BANNER} */`, "", ":root {", "  /* Color */"];

  for (const [key, c] of Object.entries(tokens.color)) {
    if (c.opacity !== undefined) {
      lines.push(`  --color-${key}: rgba(${hexToRgbTriplet(c.value)}, ${c.opacity});`);
      lines.push(`  --color-${key}-hex: ${c.value};`);
    } else {
      lines.push(`  --color-${key}: ${c.value};`);
    }
  }

  lines.push("", "  /* Typography */");
  for (const [key, t] of Object.entries(tokens.typography)) {
    const kebab = toKebab(key);
    lines.push(`  --font-${kebab}-family: "${t.family}";`);
    lines.push(`  --font-${kebab}-size: ${t.size}px;`);
    lines.push(`  --font-${kebab}-weight: ${t.weight};`);
    lines.push(`  --font-${kebab}-line-height: ${t.lineHeight};`);
    lines.push(`  --font-${kebab}-letter-spacing: ${t.letterSpacing}px;`);
    lines.push(`  --font-${kebab}-text-transform: ${t.textTransform};`);
  }

  lines.push("", "  /* Spacing */");
  for (const [key, v] of Object.entries(tokens.spacing)) {
    lines.push(`  --space-${key}: ${v}px;`);
  }

  lines.push("", "  /* Radius */");
  for (const [key, v] of Object.entries(tokens.radius)) {
    lines.push(`  --radius-${key}: ${v}px;`);
  }

  lines.push("", "  /* Component geometry */");
  for (const [groupKey, group] of Object.entries(tokens.component)) {
    const groupKebab = toKebab(groupKey);
    for (const [k, v] of Object.entries(group)) {
      const kKebab = toKebab(k);
      if (k.endsWith("Token")) {
        const { category, key } = splitRef(v);
        const outKey = kKebab.replace(/-token$/, "");
        const varRef = category === "radius" ? `var(--radius-${key})` : `var(--color-${key})`;
        lines.push(`  --component-${groupKebab}-${outKey}: ${varRef};`);
      } else {
        const unit = typeof v === "number" ? "px" : "";
        lines.push(`  --component-${groupKebab}-${kKebab}: ${v}${unit};`);
      }
    }
  }

  lines.push("}", "");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// apps/ios/Sources/SwabCore/Generated/DesignTokens.swift
// ---------------------------------------------------------------------------

function buildSwift() {
  const lines = [
    `// ${BANNER}`,
    "//",
    "// Design tokens for the Nuit theme — plain hex strings and numeric",
    "// constants, no SwiftUI import, so SwabCore stays UI-framework-free",
    "// (same convention as Carte/CarteTheme.swift). `SwabUI`'s `Color(hex:)`",
    "// converts these to `Color` at the view layer.",
    "public enum DesignTokens {",
    "    public enum Color {",
  ];

  for (const [key, c] of Object.entries(tokens.color)) {
    const name = toCamel(key);
    lines.push(`        public static let ${name} = "${c.value}"`);
    if (c.opacity !== undefined) {
      lines.push(`        public static let ${name}Opacity: Double = ${c.opacity}`);
    }
  }
  lines.push("    }", "");

  lines.push(
    "    public struct TypographyStyle {",
    "        public let family: String",
    "        public let size: Double",
    "        public let weight: Int",
    "        public let lineHeight: Double",
    "        public let letterSpacing: Double",
    "        public let textTransform: String",
    "",
    "        public init(family: String, size: Double, weight: Int, lineHeight: Double, letterSpacing: Double, textTransform: String) {",
    "            self.family = family",
    "            self.size = size",
    "            self.weight = weight",
    "            self.lineHeight = lineHeight",
    "            self.letterSpacing = letterSpacing",
    "            self.textTransform = textTransform",
    "        }",
    "    }",
    "",
  );

  lines.push("    public enum Typography {");
  for (const [key, t] of Object.entries(tokens.typography)) {
    lines.push(
      `        public static let ${key} = TypographyStyle(family: "${t.family}", size: ${t.size}, weight: ${t.weight}, lineHeight: ${t.lineHeight}, letterSpacing: ${t.letterSpacing}, textTransform: "${t.textTransform}")`,
    );
  }
  lines.push("    }", "");

  lines.push("    public enum Spacing {");
  for (const [key, v] of Object.entries(tokens.spacing)) {
    lines.push(`        public static let ${toCamel(key)}: Double = ${v}`);
  }
  lines.push("    }", "");

  lines.push("    public enum Radius {");
  for (const [key, v] of Object.entries(tokens.radius)) {
    lines.push(`        public static let ${toCamel(key)}: Double = ${v}`);
  }
  lines.push("    }", "");

  lines.push("    public enum Component {");
  for (const [groupKey, group] of Object.entries(tokens.component)) {
    const typeName = pascalCase(groupKey);
    lines.push(`        public enum ${typeName} {`);
    for (const [k, v] of Object.entries(group)) {
      if (k.endsWith("Token")) {
        const { category, key } = splitRef(v);
        const outName = toCamel(k.slice(0, -"Token".length));
        const refExpr = category === "radius" ? `Radius.${toCamel(key)}` : `Color.${toCamel(key)}`;
        const swiftType = category === "radius" ? "Double" : "String";
        lines.push(`            public static let ${outName}: ${swiftType} = ${refExpr}`);
      } else {
        const name = toCamel(k);
        const isString = typeof v === "string";
        lines.push(
          `            public static let ${name}: ${isString ? "String" : "Double"} = ${isString ? `"${v}"` : v}`,
        );
      }
    }
    lines.push("        }");
  }
  lines.push("    }", "}", "");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// apps/android/.../ui/theme/DesignTokens.kt
// ---------------------------------------------------------------------------

function buildKotlin() {
  const lines = [
    "package com.swab.android.ui.theme",
    "",
    `// ${BANNER}`,
    "//",
    "// Design tokens for the Nuit theme — plain hex strings and numeric",
    "// constants, no Compose/Android imports, so this stays plain-JVM-testable",
    "// (same convention as carte/EtatColors.kt).",
    "object DesignTokens {",
    "    object Color {",
  ];

  for (const [key, c] of Object.entries(tokens.color)) {
    const name = toUpperSnake(key);
    lines.push(`        const val ${name} = "${c.value}"`);
    if (c.opacity !== undefined) {
      lines.push(`        const val ${name}_OPACITY = ${c.opacity}`);
    }
  }
  lines.push("    }", "");

  lines.push(
    "    data class TypographyStyle(",
    "        val family: String,",
    "        val size: Double,",
    "        val weight: Int,",
    "        val lineHeight: Double,",
    "        val letterSpacing: Double,",
    "        val textTransform: String,",
    "    )",
    "",
  );

  lines.push("    object Typography {");
  for (const [key, t] of Object.entries(tokens.typography)) {
    lines.push(
      `        val ${toUpperSnake(key)} = TypographyStyle(family = "${t.family}", size = ${toKotlinDouble(t.size)}, weight = ${t.weight}, lineHeight = ${toKotlinDouble(t.lineHeight)}, letterSpacing = ${toKotlinDouble(t.letterSpacing)}, textTransform = "${t.textTransform}")`,
    );
  }
  lines.push("    }", "");

  lines.push("    object Spacing {");
  for (const [key, v] of Object.entries(tokens.spacing)) {
    lines.push(`        const val ${toUpperSnake(key)} = ${toKotlinDouble(v)}`);
  }
  lines.push("    }", "");

  lines.push("    object Radius {");
  for (const [key, v] of Object.entries(tokens.radius)) {
    lines.push(`        const val ${toUpperSnake(key)} = ${toKotlinDouble(v)}`);
  }
  lines.push("    }", "");

  lines.push("    object Component {");
  for (const [groupKey, group] of Object.entries(tokens.component)) {
    const typeName = pascalCase(groupKey);
    lines.push(`        object ${typeName} {`);
    for (const [k, v] of Object.entries(group)) {
      if (k.endsWith("Token")) {
        const { category, key } = splitRef(v);
        const outName = toUpperSnake(k.slice(0, -"Token".length));
        const refExpr = category === "radius" ? `Radius.${toUpperSnake(key)}` : `Color.${toUpperSnake(key)}`;
        lines.push(`            val ${outName} = ${refExpr}`);
      } else {
        const name = toUpperSnake(k);
        const isString = typeof v === "string";
        if (isString) {
          lines.push(`            const val ${name} = "${v}"`);
        } else {
          lines.push(`            const val ${name} = ${toKotlinDouble(v)}`);
        }
      }
    }
    lines.push("        }");
  }
  lines.push("    }", "}", "");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Write / check
// ---------------------------------------------------------------------------

const outputs = [
  { path: "packages/ui/src/tokens.ts", content: buildTs() },
  { path: "packages/ui/src/tokens.css", content: buildCss() },
  { path: "apps/ios/Sources/SwabCore/Generated/DesignTokens.swift", content: buildSwift() },
  {
    path: "apps/android/app/src/main/kotlin/com/swab/android/ui/theme/DesignTokens.kt",
    content: buildKotlin(),
  },
];

let drift = false;
for (const { path, content } of outputs) {
  const abs = join(repoRoot, path);
  const existing = existsSync(abs) ? readFileSync(abs, "utf8") : null;
  if (existing === content) continue;

  if (check) {
    drift = true;
    console.error(`STALE: ${path}`);
    continue;
  }

  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
  console.log(`wrote ${path}`);
}

if (check) {
  if (drift) {
    console.error("Design tokens are stale — run `node packages/ui/scripts/generate.mjs`.");
    process.exit(1);
  }
  console.log("Design tokens up to date.");
} else {
  console.log("Design tokens generated.");
}
