// GENERATED by packages/ui/scripts/generate.mjs from packages/ui/tokens/tokens.json — DO NOT EDIT BY HAND.

export const colors = {
  "nuit": "#0f1426",
  "encre": "#171e38",
  "voile": "#202949",
  "voile-2": "#28325a",
  "hair": { value: "#edebe2", opacity: 0.12 },
  "hair-fort": { value: "#edebe2", opacity: 0.22 },
  "ivoire": "#edebe2",
  "brume": "#9aa1c2",
  "ombre": "#8a91b5",
  "etoile": "#e4be6a",
  "etoile-encre": "#1c1505",
  "etoile-voile": { value: "#e4be6a", opacity: 0.14 },
  "etoile-piste": { value: "#e4be6a", opacity: 0.3 },
  "etoile-lueur": { value: "#e4be6a", opacity: 0.05 },
  "sauge": "#6fbfa3",
  "ciel": "#84a9e6",
  "corail": "#d98a73",
} as const;

export const typography = {
  wordmark: { family: "Space Grotesk", size: 26, weight: 500, lineHeight: 1.25, letterSpacingEm: 0.22, textTransform: "none" },
  title: { family: "Space Grotesk", size: 20, weight: 500, lineHeight: 1.25, letterSpacingEm: 0, textTransform: "none" },
  doneTitle: { family: "Space Grotesk", size: 16, weight: 500, lineHeight: 1.25, letterSpacingEm: 0, textTransform: "none" },
  base: { family: "Inter", size: 15, weight: 400, lineHeight: 1.6, letterSpacingEm: 0, textTransform: "none" },
  button: { family: "Inter", size: 15, weight: 500, lineHeight: 1.2, letterSpacingEm: 0, textTransform: "none" },
  subtitle: { family: "Inter", size: 13.5, weight: 400, lineHeight: 1.5, letterSpacingEm: 0, textTransform: "none" },
  tag: { family: "Inter", size: 14, weight: 400, lineHeight: 1.3, letterSpacingEm: 0, textTransform: "none" },
  caption: { family: "Inter", size: 12, weight: 400, lineHeight: 1.5, letterSpacingEm: 0, textTransform: "none" },
  label: { family: "Inter", size: 11, weight: 400, lineHeight: 1.3, letterSpacingEm: 0.1, textTransform: "uppercase" },
} as const;

export const spacing = {
  xs: 4,
  s: 8,
  sm: 12,
  m: 14,
  ml: 16,
  l: 20,
  xl: 24,
} as const;

export const radius = {
  button: 12,
  input: 10,
  pill: 999,
  card: 12,
  tile: 14,
} as const;

export const component = {
  button: {
    height: 48,
    radius: radius.button,
    paddingHorizontal: 14,
  },
  tag: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    radius: radius.pill,
  },
  segmentedControl: {
    cellPaddingVertical: 10,
    cellPaddingHorizontal: 2,
  },
  border: {
    defaultWidth: 1,
    defaultColor: colors["hair"],
    interactiveColor: colors["hair-fort"],
  },
  textField: {
    radius: radius.input,
  },
  otp: {
    radius: radius.input,
  },
  screen: {
    paddingTop: 14,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
} as const;

export const motion = {
  screenTransition: {
    durationMs: 280,
    riseDistance: 4,
    easing: "ease",
  },
  borderTransition: {
    durationMs: 150,
  },
  controlTransition: {
    durationMs: 200,
  },
  pressScale: 0.985,
  reducedMotion: "disable-all",
} as const;
