package com.swab.android.ui.theme

// GENERATED by packages/ui/scripts/generate.mjs from packages/ui/tokens/tokens.json — DO NOT EDIT BY HAND.
//
// Design tokens for the Nuit theme — plain hex strings and numeric
// constants, no Compose/Android imports, so this stays plain-JVM-testable
// (same convention as carte/EtatColors.kt).
object DesignTokens {
    object Color {
        const val NUIT = "#0f1426"
        const val ENCRE = "#171e38"
        const val VOILE = "#202949"
        const val VOILE_2 = "#28325a"
        const val HAIR = "#edebe2"
        const val HAIR_OPACITY = 0.12
        const val HAIR_FORT = "#edebe2"
        const val HAIR_FORT_OPACITY = 0.22
        const val IVOIRE = "#edebe2"
        const val BRUME = "#9aa1c2"
        const val OMBRE = "#8a91b5"
        const val ETOILE = "#e4be6a"
        const val ETOILE_ENCRE = "#1c1505"
        const val ETOILE_VOILE = "#e4be6a"
        const val ETOILE_VOILE_OPACITY = 0.14
        const val ETOILE_PISTE = "#e4be6a"
        const val ETOILE_PISTE_OPACITY = 0.3
        const val ETOILE_LUEUR = "#e4be6a"
        const val ETOILE_LUEUR_OPACITY = 0.05
        const val SAUGE = "#6fbfa3"
        const val CIEL = "#84a9e6"
        const val CORAIL = "#d98a73"
        const val ETAT_DISPONIBLE = "#8fb59a"
        const val ETAT_OCCUPE = "#c8917e"
        const val ETAT_AILLEURS = "#8aa0be"
    }

    data class TypographyStyle(
        val family: String,
        val size: Double,
        val weight: Int,
        val lineHeight: Double,
        val letterSpacingEm: Double,
        val textTransform: String,
    )

    object Typography {
        val WORDMARK = TypographyStyle(family = "Space Grotesk", size = 26.0, weight = 500, lineHeight = 1.25, letterSpacingEm = 0.22, textTransform = "none")
        val TITLE = TypographyStyle(family = "Space Grotesk", size = 20.0, weight = 500, lineHeight = 1.25, letterSpacingEm = 0.0, textTransform = "none")
        val DONE_TITLE = TypographyStyle(family = "Space Grotesk", size = 16.0, weight = 500, lineHeight = 1.25, letterSpacingEm = 0.0, textTransform = "none")
        val BASE = TypographyStyle(family = "Inter", size = 15.0, weight = 400, lineHeight = 1.6, letterSpacingEm = 0.0, textTransform = "none")
        val BUTTON = TypographyStyle(family = "Inter", size = 15.0, weight = 500, lineHeight = 1.2, letterSpacingEm = 0.0, textTransform = "none")
        val SUBTITLE = TypographyStyle(family = "Inter", size = 13.5, weight = 400, lineHeight = 1.5, letterSpacingEm = 0.0, textTransform = "none")
        val TAG = TypographyStyle(family = "Inter", size = 14.0, weight = 400, lineHeight = 1.3, letterSpacingEm = 0.0, textTransform = "none")
        val CAPTION = TypographyStyle(family = "Inter", size = 12.0, weight = 400, lineHeight = 1.5, letterSpacingEm = 0.0, textTransform = "none")
        val LABEL = TypographyStyle(family = "Inter", size = 11.0, weight = 400, lineHeight = 1.3, letterSpacingEm = 0.1, textTransform = "uppercase")
    }

    object Spacing {
        const val XS = 4.0
        const val S = 8.0
        const val SM = 12.0
        const val M = 14.0
        const val ML = 16.0
        const val L = 20.0
        const val XL = 24.0
    }

    object Radius {
        const val BUTTON = 12.0
        const val INPUT = 10.0
        const val PILL = 999.0
        const val CARD = 12.0
        const val TILE = 14.0
    }

    object Component {
        object Button {
            const val HEIGHT = 48.0
            val RADIUS = Radius.BUTTON
            const val PADDING_HORIZONTAL = 14.0
        }
        object Tag {
            const val PADDING_VERTICAL = 8.0
            const val PADDING_HORIZONTAL = 14.0
            val RADIUS = Radius.PILL
        }
        object SegmentedControl {
            const val CELL_PADDING_VERTICAL = 10.0
            const val CELL_PADDING_HORIZONTAL = 2.0
        }
        object Border {
            const val DEFAULT_WIDTH = 1.0
            val DEFAULT_COLOR = Color.HAIR
            val INTERACTIVE_COLOR = Color.HAIR_FORT
        }
        object TextField {
            val RADIUS = Radius.INPUT
        }
        object OTP {
            val RADIUS = Radius.INPUT
        }
        object Screen {
            const val PADDING_TOP = 14.0
            const val PADDING_HORIZONTAL = 20.0
            const val PADDING_BOTTOM = 20.0
        }
    }

    object Motion {
        object ScreenTransition {
            const val DURATION_MS = 280.0
            const val RISE_DISTANCE = 4.0
            const val EASING = "ease"
        }
        object BorderTransition {
            const val DURATION_MS = 150.0
        }
        object ControlTransition {
            const val DURATION_MS = 200.0
        }
        const val PRESS_SCALE = 0.985
        const val REDUCED_MOTION = "disable-all"
    }
}
