package com.swab.android.ui.theme

// GENERATED by packages/ui/scripts/generate.mjs from packages/ui/tokens/tokens.json — DO NOT EDIT BY HAND.
//
// Design tokens for the Nuit theme — plain hex strings and numeric
// constants, no Compose/Android imports, so this stays plain-JVM-testable
// (same convention as carte/EtatColors.kt).
object DesignTokens {
    object Color {
        const val NUIT = "#0f1426"
        const val ENCRE = "#171e38"
        const val VOILE = "#202949"
        const val VOILE_2 = "#28325a"
        const val HAIR = "#edebe2"
        const val HAIR_OPACITY = 0.12
        const val HAIR_FORT = "#edebe2"
        const val HAIR_FORT_OPACITY = 0.22
        const val IVOIRE = "#edebe2"
        const val BRUME = "#9aa1c2"
        const val OMBRE = "#6a7194"
        const val ETOILE = "#e4be6a"
        const val ETOILE_ENCRE = "#1c1505"
        const val SAUGE = "#6fbfa3"
        const val CIEL = "#84a9e6"
        const val CORAIL = "#d98a73"
    }

    data class TypographyStyle(
        val family: String,
        val size: Double,
        val weight: Int,
        val lineHeight: Double,
        val letterSpacing: Double,
        val textTransform: String,
    )

    object Typography {
        val WORDMARK = TypographyStyle(family = "Space Grotesk", size = 26.0, weight = 500, lineHeight = 1.25, letterSpacing = 5.7, textTransform = "none")
        val TITLE = TypographyStyle(family = "Space Grotesk", size = 20.0, weight = 500, lineHeight = 1.25, letterSpacing = 0.0, textTransform = "none")
        val DONE_TITLE = TypographyStyle(family = "Space Grotesk", size = 16.0, weight = 500, lineHeight = 1.25, letterSpacing = 0.0, textTransform = "none")
        val BASE = TypographyStyle(family = "Inter", size = 15.0, weight = 400, lineHeight = 1.6, letterSpacing = 0.0, textTransform = "none")
        val BUTTON = TypographyStyle(family = "Inter", size = 15.0, weight = 500, lineHeight = 1.2, letterSpacing = 0.0, textTransform = "none")
        val SUBTITLE = TypographyStyle(family = "Inter", size = 13.5, weight = 400, lineHeight = 1.5, letterSpacing = 0.0, textTransform = "none")
        val TAG = TypographyStyle(family = "Inter", size = 14.0, weight = 400, lineHeight = 1.3, letterSpacing = 0.0, textTransform = "none")
        val CAPTION = TypographyStyle(family = "Inter", size = 12.0, weight = 400, lineHeight = 1.5, letterSpacing = 0.0, textTransform = "none")
        val LABEL = TypographyStyle(family = "Inter", size = 11.0, weight = 400, lineHeight = 1.3, letterSpacing = 1.1, textTransform = "uppercase")
    }

    object Spacing {
        const val XS = 4.0
        const val S = 8.0
        const val SM = 12.0
        const val M = 16.0
        const val L = 24.0
        const val XL = 32.0
    }

    object Radius {
        const val BUTTON = 12.0
        const val INPUT = 10.0
        const val PILL = 999.0
        const val CARD = 12.0
        const val TILE = 14.0
    }

    object Component {
        object Button {
            const val HEIGHT = 48.0
            val RADIUS = Radius.BUTTON
            const val PADDING_HORIZONTAL = 14.0
        }
        object Tag {
            const val PADDING_VERTICAL = 8.0
            const val PADDING_HORIZONTAL = 14.0
            val RADIUS = Radius.PILL
        }
        object SegmentedControl {
            const val CELL_PADDING_VERTICAL = 10.0
            const val CELL_PADDING_HORIZONTAL = 2.0
        }
        object Border {
            const val DEFAULT_WIDTH = 1.0
            val DEFAULT_COLOR = Color.HAIR
            val INTERACTIVE_COLOR = Color.HAIR_FORT
        }
        object TextField {
            val RADIUS = Radius.INPUT
        }
        object OTP {
            val RADIUS = Radius.INPUT
        }
    }
}
